Update README.md
AttributeError: module 'tsdb' has no attribute 'list_available_datasets' . It seems that `list_available_datasets` has been replaced to `list`