Update README.md (#57)
* Update README.md

AttributeError: module 'tsdb' has no attribute 'list_available_datasets' . It seems that `list_available_datasets` has been replaced to `list`

---------

Co-authored-by: Wenjie Du <wenjay.du@gmail.com>